name: ${pluginName}
main: vg.civcraft.mc.namelayer.NameLayerPlugin
version: ${version}
author: Rourke750
authors: [BlackXnt, Maxopoly, ProgrammerDan, Tyrothalos, Scuwr, Mr_Little_Kitty]
depend: [CivModCore]
api-version: ${api_version}
description: ${description}
permissions:
  namelayer.admin:
    default: op
